

export const GET_RECENT_CONVOS = "GET_RECENT_CONVOS"
export const GET_USERS = "GET_USERS"
export const GET_USER = "GET_USER"
export const GET_CONVERSATION = "GET_CONVERSATION"
export const GET_CHANNELS = "GET_CHANNELS"
export const ADD_CONVO = "ADD_CONVO"
export const GET_CONVERSATIONS = "GET_CONVERSATIONS"
export const START_NEW_CONVO = "START_NEW_CONVO"